[licenses]
allow = ["Apache-2.0", "Apache-2.0 WITH LLVM-exception", "MIT", "ISC"]
exceptions = [
    { allow = [
        "Zlib",
    ], crate = "tinyvec" },
    { allow = [
        "Unicode-DFS-2016",
    ], crate = "unicode-ident" },
    { allow = [
        "OpenSSL",
    ], crate = "ring" },
]

[[licenses.clarify]]
crate = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
